<?php
/*
 * MIT License
 *
 * Copyright (c) 2023 Techyouknow
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/** @var \Techyouknow\SocialLogin\Block\SocialBlock $block */
?>

<?php if($block->IsSocialLoginActive() && count($block->getEnabledSocialNetworks()) > 0): ?>
<div class="block block-social-login">
    <!-- Social Login container -->
    <div class="social-login-container">
        <div class="seperator">
            <strong>or</strong>
        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <ul>
                <?php foreach($block->getEnabledSocialNetworks() as $key => $socialNetwork): ?>
                <li><a class="<?= $key ?>" href="#">Sign In with&nbsp;<span><?= $key ?></span></a></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <!-- End Social Login container -->

    <script type="text/x-magento-init">
        {
            "*": {
                "providerWindowOpener": {}
            }
        }
    </script>
</div>
<?php endif; ?>
